show_personal_inbox:
  type: enum
  default: "All users"
  choices:
    - "All users"
    - "Those, who can send PMs"
    - "Nobody"
use_group_page_inbox:
  type: bool
  default: false
hide_group_inboxes:
  type: list
  list_type: group
  default: ""  
advanced_group_inbox_configuration:
  type: objects
  default: []
  schema:
    name: group
    identifier: custom_name
    properties:
      group:
        type: groups
        required: true
        validations:
          max: 1
      custom_name:
        type: string
        required: false
