show_personal_inbox:
  type: enum
  default: "All users"
  choices:
    - "All users"
    - "Those, who can send PMs"
    - "Nobody"
use_group_page_inbox:
  type: bool
  default: false
hide_group_inboxes:
  type: list
  list_type: group
  default: ""